name: mp3_player
description: MP3/M4A player with no-copy file access and resume-from-last-position.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.40
  shared_preferences: ^2.2.3
  audio_service: ^0.18.15

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
